export const GETLISTMOVIES = 'GETLISTMOVIES';

export const GETDETAILMOVIES = 'GETDETAILMOVIES';

export const SEARCHMOVIES = 'SEARCHMOVIES';

export const GETMOVIESTRENDINGWEEKLY = 'GETMOVIESTRENDINGWEEKLY';

export const GETNOWPLAYING = 'GETNOWPLAYING';

export const GETPOPULARMOVIES = 'GETPOPULARMOVIES';

export const GETTOPRATEDMOVIES = 'GETTOPRATEDMOVIES';

export const GETUPCOMINGMOVIES = 'GETUPCOMINGMOVIES';